name: "send email after workflow"
on:
    workflow_dispatch:

jobs:
    send_email:
        runs-on: ubuntu-latest
        steps:
            - name: "send email"
              uses: actions/checkout@v2
            
            - name: "send python"
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
            
            - name: "install dependencies"
              run:
                python -m install --upgrade pip
            
            - name: "send mail by executing python script"
              run:  python script.py
              env:
                WORKFLOW_NAME: ${{ github.workflow }}
                REPO_NAME: ${{ github.repository }}
                WORKFLOW_RUN_ID: ${{ github.run_id }}
                SENDER_PASSWORDS: ${{ secrets.SENDER_PASSWORDS }}
                SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
                RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}





            
